<?php

/**
 * BaseReunion
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $Proyecto_id
 * @property integer $Persona_id
 * @property string $Titulo
 * @property clob $Descripcion
 * @property clob $Anotaciones
 * @property timestamp $Fecha
 * @property integer $Duracion
 * @property boolean $is_activated
 * @property Proyecto $Proyecto
 * @property Persona $Persona
 * 
 * @method integer   getId()           Returns the current record's "id" value
 * @method integer   getProyectoId()   Returns the current record's "Proyecto_id" value
 * @method integer   getPersonaId()    Returns the current record's "Persona_id" value
 * @method string    getTitulo()       Returns the current record's "Titulo" value
 * @method clob      getDescripcion()  Returns the current record's "Descripcion" value
 * @method clob      getAnotaciones()  Returns the current record's "Anotaciones" value
 * @method timestamp getFecha()        Returns the current record's "Fecha" value
 * @method integer   getDuracion()     Returns the current record's "Duracion" value
 * @method boolean   getIsActivated()  Returns the current record's "is_activated" value
 * @method Proyecto  getProyecto()     Returns the current record's "Proyecto" value
 * @method Persona   getPersona()      Returns the current record's "Persona" value
 * @method Reunion   setId()           Sets the current record's "id" value
 * @method Reunion   setProyectoId()   Sets the current record's "Proyecto_id" value
 * @method Reunion   setPersonaId()    Sets the current record's "Persona_id" value
 * @method Reunion   setTitulo()       Sets the current record's "Titulo" value
 * @method Reunion   setDescripcion()  Sets the current record's "Descripcion" value
 * @method Reunion   setAnotaciones()  Sets the current record's "Anotaciones" value
 * @method Reunion   setFecha()        Sets the current record's "Fecha" value
 * @method Reunion   setDuracion()     Sets the current record's "Duracion" value
 * @method Reunion   setIsActivated()  Sets the current record's "is_activated" value
 * @method Reunion   setProyecto()     Sets the current record's "Proyecto" value
 * @method Reunion   setPersona()      Sets the current record's "Persona" value
 * 
 * @package    scrum
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseReunion extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('reunion');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('Proyecto_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('Persona_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('Titulo', 'string', 45, array(
             'type' => 'string',
             'length' => 45,
             ));
        $this->hasColumn('Descripcion', 'clob', 65535, array(
             'type' => 'clob',
             'length' => 65535,
             ));
        $this->hasColumn('Anotaciones', 'clob', 65535, array(
             'type' => 'clob',
             'length' => 65535,
             ));
        $this->hasColumn('Fecha', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('Duracion', 'integer', 1, array(
             'type' => 'integer',
             'length' => 1,
             ));
        $this->hasColumn('is_activated', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => 1,
             ));


        $this->index('fk_Reunion_Proyecto1', array(
             'fields' => 
             array(
              0 => 'Proyecto_id',
             ),
             ));
        $this->index('fk_Reunion_Persona1', array(
             'fields' => 
             array(
              0 => 'Persona_id',
             ),
             ));
        $this->option('collate', 'latin1_spanish_ci');
        $this->option('charset', 'latin1');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Proyecto', array(
             'local' => 'Proyecto_id',
             'foreign' => 'id'));

        $this->hasOne('Persona', array(
             'local' => 'Persona_id',
             'foreign' => 'id'));
    }
}