<?php

/**
 * BaseSprintProductBacklog
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idSprint
 * @property integer $idProductBacklog
 * @property Sprint $idSprint
 * @property ProductBacklog $idProductBacklog
 * 
 * @method Sprint               getIdSprint()         Returns the current record's "idSprint" value
 * @method ProductBacklog       getIdProductBacklog() Returns the current record's "idProductBacklog" value
 * @method SprintProductBacklog setIdSprint()         Sets the current record's "idSprint" value
 * @method SprintProductBacklog setIdProductBacklog() Sets the current record's "idProductBacklog" value
 * 
 * @package    scrum
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSprintProductBacklog extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('sprint_product_backlog');
        $this->hasColumn('idSprint', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('idProductBacklog', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 4,
             ));


        $this->index('fk_Sprint_has_ProductBacklog_ProductBacklog1_idx', array(
             'fields' => 
             array(
              0 => 'idProductBacklog',
             ),
             ));
        $this->index('fk_Sprint_has_ProductBacklog_Sprint1_idx', array(
             'fields' => 
             array(
              0 => 'idSprint',
             ),
             ));
        $this->option('collate', 'latin1_spanish_ci');
        $this->option('charset', 'latin1');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Sprint as idSprint', array(
             'local' => 'idSprint',
             'foreign' => 'idSprint'));

        $this->hasOne('ProductBacklog as idProductBacklog', array(
             'local' => 'idProductBacklog',
             'foreign' => 'idProductBacklog'));
    }
}