<?php

/**
 * BaseReunion
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idReunion
 * @property string $Titulo
 * @property string $Descripcion
 * @property string $Anotaciones
 * @property timestamp $Fecha
 * @property integer $Duracion
 * @property integer $idProyecto
 * @property integer $idPersona
 * @property boolean $Activo
 * @property Proyecto $idProyecto
 * @property Persona $idPersona
 * 
 * @method integer   getIdReunion()   Returns the current record's "idReunion" value
 * @method string    getTitulo()      Returns the current record's "Titulo" value
 * @method string    getDescripcion() Returns the current record's "Descripcion" value
 * @method string    getAnotaciones() Returns the current record's "Anotaciones" value
 * @method timestamp getFecha()       Returns the current record's "Fecha" value
 * @method integer   getDuracion()    Returns the current record's "Duracion" value
 * @method Proyecto  getIdProyecto()  Returns the current record's "idProyecto" value
 * @method Persona   getIdPersona()   Returns the current record's "idPersona" value
 * @method boolean   getActivo()      Returns the current record's "Activo" value
 * @method Reunion   setIdReunion()   Sets the current record's "idReunion" value
 * @method Reunion   setTitulo()      Sets the current record's "Titulo" value
 * @method Reunion   setDescripcion() Sets the current record's "Descripcion" value
 * @method Reunion   setAnotaciones() Sets the current record's "Anotaciones" value
 * @method Reunion   setFecha()       Sets the current record's "Fecha" value
 * @method Reunion   setDuracion()    Sets the current record's "Duracion" value
 * @method Reunion   setIdProyecto()  Sets the current record's "idProyecto" value
 * @method Reunion   setIdPersona()   Sets the current record's "idPersona" value
 * @method Reunion   setActivo()      Sets the current record's "Activo" value
 * 
 * @package    scrum
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseReunion extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('reunion');
        $this->hasColumn('idReunion', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('Titulo', 'string', 45, array(
             'type' => 'string',
             'length' => 45,
             ));
        $this->hasColumn('Descripcion', 'string', 45, array(
             'type' => 'string',
             'length' => 45,
             ));
        $this->hasColumn('Anotaciones', 'string', 45, array(
             'type' => 'string',
             'length' => 45,
             ));
        $this->hasColumn('Fecha', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('Duracion', 'integer', 1, array(
             'type' => 'integer',
             'length' => 1,
             ));
        $this->hasColumn('idProyecto', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('idPersona', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('Activo', 'boolean', null, array(
             'type' => 'boolean',
             ));


        $this->index('fk_Reunion_Proyecto1_idx', array(
             'fields' => 
             array(
              0 => 'idProyecto',
             ),
             ));
        $this->index('fk_Reunion_Persona1_idx', array(
             'fields' => 
             array(
              0 => 'idPersona',
             ),
             ));
        $this->option('collate', 'latin1_spanish_ci');
        $this->option('charset', 'latin1');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Proyecto as idProyecto', array(
             'local' => 'idProyecto',
             'foreign' => 'idProyecto'));

        $this->hasOne('Persona as idPersona', array(
             'local' => 'idPersona',
             'foreign' => 'idPersona'));
    }
}