<?php

/**
 * BaseRol
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idRol
 * @property string $Nombre
 * @property string $Descripcion
 * @property boolean $Activo
 * @property Doctrine_Collection $Equipoes
 * 
 * @method integer             getIdRol()       Returns the current record's "idRol" value
 * @method string              getNombre()      Returns the current record's "Nombre" value
 * @method string              getDescripcion() Returns the current record's "Descripcion" value
 * @method boolean             getActivo()      Returns the current record's "Activo" value
 * @method Doctrine_Collection getEquipoes()    Returns the current record's "Equipoes" collection
 * @method Rol                 setIdRol()       Sets the current record's "idRol" value
 * @method Rol                 setNombre()      Sets the current record's "Nombre" value
 * @method Rol                 setDescripcion() Sets the current record's "Descripcion" value
 * @method Rol                 setActivo()      Sets the current record's "Activo" value
 * @method Rol                 setEquipoes()    Sets the current record's "Equipoes" collection
 * 
 * @package    scrum
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseRol extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('rol');
        $this->hasColumn('idRol', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('Nombre', 'string', 45, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 45,
             ));
        $this->hasColumn('Descripcion', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
        $this->hasColumn('Activo', 'boolean', null, array(
             'type' => 'boolean',
             ));

        $this->option('collate', 'latin1_spanish_ci');
        $this->option('charset', 'latin1');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Equipo as Equipoes', array(
             'local' => 'idRol',
             'foreign' => 'idRol'));
    }
}