<?php

/**
 * BaseEquipo
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idEquipo
 * @property integer $idRol
 * @property integer $idPersona
 * @property integer $idProyecto
 * @property string $Nombre
 * @property boolean $Activo
 * @property Rol $idRol
 * @property Persona $idPersona
 * @property Proyecto $idProyecto
 * 
 * @method integer  getIdEquipo()   Returns the current record's "idEquipo" value
 * @method Rol      getIdRol()      Returns the current record's "idRol" value
 * @method Persona  getIdPersona()  Returns the current record's "idPersona" value
 * @method Proyecto getIdProyecto() Returns the current record's "idProyecto" value
 * @method string   getNombre()     Returns the current record's "Nombre" value
 * @method boolean  getActivo()     Returns the current record's "Activo" value
 * @method Equipo   setIdEquipo()   Sets the current record's "idEquipo" value
 * @method Equipo   setIdRol()      Sets the current record's "idRol" value
 * @method Equipo   setIdPersona()  Sets the current record's "idPersona" value
 * @method Equipo   setIdProyecto() Sets the current record's "idProyecto" value
 * @method Equipo   setNombre()     Sets the current record's "Nombre" value
 * @method Equipo   setActivo()     Sets the current record's "Activo" value
 * 
 * @package    scrum
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseEquipo extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('equipo');
        $this->hasColumn('idEquipo', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('idRol', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('idPersona', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('idProyecto', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('Nombre', 'string', 45, array(
             'type' => 'string',
             'length' => 45,
             ));
        $this->hasColumn('Activo', 'boolean', null, array(
             'type' => 'boolean',
             ));


        $this->index('fk_Equipo_Rol1_idx', array(
             'fields' => 
             array(
              0 => 'idRol',
             ),
             ));
        $this->index('fk_Equipo_Persona1_idx', array(
             'fields' => 
             array(
              0 => 'idPersona',
             ),
             ));
        $this->index('fk_Equipo_Proyecto1_idx', array(
             'fields' => 
             array(
              0 => 'idProyecto',
             ),
             ));
        $this->option('collate', 'latin1_spanish_ci');
        $this->option('charset', 'latin1');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Rol as idRol', array(
             'local' => 'idRol',
             'foreign' => 'idRol'));

        $this->hasOne('Persona as idPersona', array(
             'local' => 'idPersona',
             'foreign' => 'idPersona'));

        $this->hasOne('Proyecto as idProyecto', array(
             'local' => 'idProyecto',
             'foreign' => 'idProyecto'));
    }
}