<?php

/**
 * BaseProductbacklog
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $Proyecto_id
 * @property integer $Persona_id
 * @property string $Nombre
 * @property clob $Descripcion
 * @property integer $Prioridad
 * @property integer $Duracion
 * @property boolean $is_activated
 * @property Proyecto $Proyecto
 * @property Persona $Persona
 * @property Doctrine_Collection $Tareas
 * @property Doctrine_Collection $SprintProductBacklogs
 * 
 * @method integer             getId()                    Returns the current record's "id" value
 * @method integer             getProyectoId()            Returns the current record's "Proyecto_id" value
 * @method integer             getPersonaId()             Returns the current record's "Persona_id" value
 * @method string              getNombre()                Returns the current record's "Nombre" value
 * @method clob                getDescripcion()           Returns the current record's "Descripcion" value
 * @method integer             getPrioridad()             Returns the current record's "Prioridad" value
 * @method integer             getDuracion()              Returns the current record's "Duracion" value
 * @method boolean             getIsActivated()           Returns the current record's "is_activated" value
 * @method Proyecto            getProyecto()              Returns the current record's "Proyecto" value
 * @method Persona             getPersona()               Returns the current record's "Persona" value
 * @method Doctrine_Collection getTareas()                Returns the current record's "Tareas" collection
 * @method Doctrine_Collection getSprintProductBacklogs() Returns the current record's "SprintProductBacklogs" collection
 * @method Productbacklog      setId()                    Sets the current record's "id" value
 * @method Productbacklog      setProyectoId()            Sets the current record's "Proyecto_id" value
 * @method Productbacklog      setPersonaId()             Sets the current record's "Persona_id" value
 * @method Productbacklog      setNombre()                Sets the current record's "Nombre" value
 * @method Productbacklog      setDescripcion()           Sets the current record's "Descripcion" value
 * @method Productbacklog      setPrioridad()             Sets the current record's "Prioridad" value
 * @method Productbacklog      setDuracion()              Sets the current record's "Duracion" value
 * @method Productbacklog      setIsActivated()           Sets the current record's "is_activated" value
 * @method Productbacklog      setProyecto()              Sets the current record's "Proyecto" value
 * @method Productbacklog      setPersona()               Sets the current record's "Persona" value
 * @method Productbacklog      setTareas()                Sets the current record's "Tareas" collection
 * @method Productbacklog      setSprintProductBacklogs() Sets the current record's "SprintProductBacklogs" collection
 * 
 * @package    scrum
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseProductbacklog extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('productbacklog');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('Proyecto_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('Persona_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('Nombre', 'string', 45, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 45,
             ));
        $this->hasColumn('Descripcion', 'clob', 65535, array(
             'type' => 'clob',
             'length' => 65535,
             ));
        $this->hasColumn('Prioridad', 'integer', 1, array(
             'type' => 'integer',
             'length' => 1,
             ));
        $this->hasColumn('Duracion', 'integer', 2, array(
             'type' => 'integer',
             'length' => 2,
             ));
        $this->hasColumn('is_activated', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => 1,
             ));


        $this->index('fk_ProductBacklog_Proyecto2', array(
             'fields' => 
             array(
              0 => 'Proyecto_id',
             ),
             ));
        $this->index('fk_ProductBacklog_Persona1', array(
             'fields' => 
             array(
              0 => 'Persona_id',
             ),
             ));
        $this->option('collate', 'latin1_spanish_ci');
        $this->option('charset', 'latin1');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Proyecto', array(
             'local' => 'Proyecto_id',
             'foreign' => 'id'));

        $this->hasOne('Persona', array(
             'local' => 'Persona_id',
             'foreign' => 'id'));

        $this->hasMany('Tarea as Tareas', array(
             'local' => 'id',
             'foreign' => 'Productbacklog_id'));

        $this->hasMany('SprintProductBacklog as SprintProductBacklogs', array(
             'local' => 'id',
             'foreign' => 'Productbacklog_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}