<?php

/**
 * BaseEstado
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idEstado
 * @property string $Nombre
 * @property string $Descripcion
 * @property Doctrine_Collection $Tareas
 * @property Doctrine_Collection $Sprints
 * 
 * @method integer             getIdEstado()    Returns the current record's "idEstado" value
 * @method string              getNombre()      Returns the current record's "Nombre" value
 * @method string              getDescripcion() Returns the current record's "Descripcion" value
 * @method Doctrine_Collection getTareas()      Returns the current record's "Tareas" collection
 * @method Doctrine_Collection getSprints()     Returns the current record's "Sprints" collection
 * @method Estado              setIdEstado()    Sets the current record's "idEstado" value
 * @method Estado              setNombre()      Sets the current record's "Nombre" value
 * @method Estado              setDescripcion() Sets the current record's "Descripcion" value
 * @method Estado              setTareas()      Sets the current record's "Tareas" collection
 * @method Estado              setSprints()     Sets the current record's "Sprints" collection
 * 
 * @package    scrum
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseEstado extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('estado');
        $this->hasColumn('idEstado', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('Nombre', 'string', 45, array(
             'type' => 'string',
             'length' => 45,
             ));
        $this->hasColumn('Descripcion', 'string', 45, array(
             'type' => 'string',
             'length' => 45,
             ));

        $this->option('collate', 'latin1_spanish_ci');
        $this->option('charset', 'latin1');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Tarea as Tareas', array(
             'local' => 'idEstado',
             'foreign' => 'idEstado'));

        $this->hasMany('Sprint as Sprints', array(
             'local' => 'idEstado',
             'foreign' => 'idEstado'));
    }
}