<?php

/**
 * BaseTarea
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $Persona_id
 * @property integer $ProductBacklog_id
 * @property integer $Estado_id
 * @property string $Nombre
 * @property clob $Descripcion
 * @property integer $TiempoEstimado
 * @property Estado $Estado
 * @property Persona $Persona
 * @property ProductBacklog $ProductBacklog
 * 
 * @method integer        getId()                Returns the current record's "id" value
 * @method integer        getPersonaId()         Returns the current record's "Persona_id" value
 * @method integer        getProductBacklogId()  Returns the current record's "ProductBacklog_id" value
 * @method integer        getEstadoId()          Returns the current record's "Estado_id" value
 * @method string         getNombre()            Returns the current record's "Nombre" value
 * @method clob           getDescripcion()       Returns the current record's "Descripcion" value
 * @method integer        getTiempoEstimado()    Returns the current record's "TiempoEstimado" value
 * @method Estado         getEstado()            Returns the current record's "Estado" value
 * @method Persona        getPersona()           Returns the current record's "Persona" value
 * @method ProductBacklog getProductBacklog()    Returns the current record's "ProductBacklog" value
 * @method Tarea          setId()                Sets the current record's "id" value
 * @method Tarea          setPersonaId()         Sets the current record's "Persona_id" value
 * @method Tarea          setProductBacklogId()  Sets the current record's "ProductBacklog_id" value
 * @method Tarea          setEstadoId()          Sets the current record's "Estado_id" value
 * @method Tarea          setNombre()            Sets the current record's "Nombre" value
 * @method Tarea          setDescripcion()       Sets the current record's "Descripcion" value
 * @method Tarea          setTiempoEstimado()    Sets the current record's "TiempoEstimado" value
 * @method Tarea          setEstado()            Sets the current record's "Estado" value
 * @method Tarea          setPersona()           Sets the current record's "Persona" value
 * @method Tarea          setProductBacklog()    Sets the current record's "ProductBacklog" value
 * 
 * @package    scrum
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTarea extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tarea');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('Persona_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('ProductBacklog_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('Estado_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('Nombre', 'string', 45, array(
             'type' => 'string',
             'length' => 45,
             ));
        $this->hasColumn('Descripcion', 'clob', 65535, array(
             'type' => 'clob',
             'length' => 65535,
             ));
        $this->hasColumn('TiempoEstimado', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));


        $this->index('fk_Tarea_Estado2', array(
             'fields' => 
             array(
              0 => 'Estado_id',
             ),
             ));
        $this->index('fk_Tarea_Persona1', array(
             'fields' => 
             array(
              0 => 'Persona_id',
             ),
             ));
        $this->index('fk_Tarea_ProductBacklog1', array(
             'fields' => 
             array(
              0 => 'ProductBacklog_id',
             ),
             ));
        $this->option('collate', 'latin1_spanish_ci');
        $this->option('charset', 'latin1');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Estado', array(
             'local' => 'Estado_id',
             'foreign' => 'id'));

        $this->hasOne('Persona', array(
             'local' => 'Persona_id',
             'foreign' => 'id'));

        $this->hasOne('ProductBacklog', array(
             'local' => 'ProductBacklog_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}