<?php

/**
 * BaseTarea
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idTarea
 * @property string $Nombre
 * @property string $Descripcion
 * @property integer $TiempoEstimado
 * @property integer $idProductBacklog
 * @property integer $idEstado
 * @property integer $idPersona
 * @property ProductBacklog $idProductBacklog
 * @property Estado $idEstado
 * @property Persona $idPersona
 * 
 * @method integer        getIdTarea()          Returns the current record's "idTarea" value
 * @method string         getNombre()           Returns the current record's "Nombre" value
 * @method string         getDescripcion()      Returns the current record's "Descripcion" value
 * @method integer        getTiempoEstimado()   Returns the current record's "TiempoEstimado" value
 * @method ProductBacklog getIdProductBacklog() Returns the current record's "idProductBacklog" value
 * @method Estado         getIdEstado()         Returns the current record's "idEstado" value
 * @method Persona        getIdPersona()        Returns the current record's "idPersona" value
 * @method Tarea          setIdTarea()          Sets the current record's "idTarea" value
 * @method Tarea          setNombre()           Sets the current record's "Nombre" value
 * @method Tarea          setDescripcion()      Sets the current record's "Descripcion" value
 * @method Tarea          setTiempoEstimado()   Sets the current record's "TiempoEstimado" value
 * @method Tarea          setIdProductBacklog() Sets the current record's "idProductBacklog" value
 * @method Tarea          setIdEstado()         Sets the current record's "idEstado" value
 * @method Tarea          setIdPersona()        Sets the current record's "idPersona" value
 * 
 * @package    scrum
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTarea extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tarea');
        $this->hasColumn('idTarea', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('Nombre', 'string', 45, array(
             'type' => 'string',
             'length' => 45,
             ));
        $this->hasColumn('Descripcion', 'string', 45, array(
             'type' => 'string',
             'length' => 45,
             ));
        $this->hasColumn('TiempoEstimado', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
        $this->hasColumn('idProductBacklog', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('idEstado', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('idPersona', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));


        $this->index('fk_Tarea_ProductBacklog_idx', array(
             'fields' => 
             array(
              0 => 'idProductBacklog',
             ),
             ));
        $this->index('fk_Tarea_Estado1_idx', array(
             'fields' => 
             array(
              0 => 'idEstado',
             ),
             ));
        $this->index('fk_Tarea_Persona1_idx', array(
             'fields' => 
             array(
              0 => 'idPersona',
             ),
             ));
        $this->option('collate', 'latin1_spanish_ci');
        $this->option('charset', 'latin1');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('ProductBacklog as idProductBacklog', array(
             'local' => 'idProductBacklog',
             'foreign' => 'idProductBacklog'));

        $this->hasOne('Estado as idEstado', array(
             'local' => 'idEstado',
             'foreign' => 'idEstado'));

        $this->hasOne('Persona as idPersona', array(
             'local' => 'idPersona',
             'foreign' => 'idPersona'));
    }
}