<?php

/**
 * BaseCambio
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idCambios
 * @property string $Descripcion
 * @property timestamp $Fecha
 * @property integer $Proyecto_idProyecto
 * @property integer $Persona_idPersona
 * @property Proyecto $ProyectoIdProyecto
 * @property Persona $PersonaIdPersona
 * 
 * @method integer   getIdCambios()           Returns the current record's "idCambios" value
 * @method string    getDescripcion()         Returns the current record's "Descripcion" value
 * @method timestamp getFecha()               Returns the current record's "Fecha" value
 * @method integer   getProyectoIdProyecto()  Returns the current record's "Proyecto_idProyecto" value
 * @method integer   getPersonaIdPersona()    Returns the current record's "Persona_idPersona" value
 * @method Proyecto  getProyectoIdProyecto()  Returns the current record's "ProyectoIdProyecto" value
 * @method Persona   getPersonaIdPersona()    Returns the current record's "PersonaIdPersona" value
 * @method Cambio    setIdCambios()           Sets the current record's "idCambios" value
 * @method Cambio    setDescripcion()         Sets the current record's "Descripcion" value
 * @method Cambio    setFecha()               Sets the current record's "Fecha" value
 * @method Cambio    setProyectoIdProyecto()  Sets the current record's "Proyecto_idProyecto" value
 * @method Cambio    setPersonaIdPersona()    Sets the current record's "Persona_idPersona" value
 * @method Cambio    setProyectoIdProyecto()  Sets the current record's "ProyectoIdProyecto" value
 * @method Cambio    setPersonaIdPersona()    Sets the current record's "PersonaIdPersona" value
 * 
 * @package    scrum
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCambio extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('Cambios');
        $this->hasColumn('idCambios', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('Descripcion', 'string', 150, array(
             'type' => 'string',
             'length' => 150,
             ));
        $this->hasColumn('Fecha', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('Proyecto_idProyecto', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('Persona_idPersona', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));


        $this->index('fk_Cambios_Proyecto1', array(
             'fields' => 
             array(
              0 => 'Proyecto_idProyecto',
             ),
             ));
        $this->index('fk_Cambios_Persona1', array(
             'fields' => 
             array(
              0 => 'Persona_idPersona',
             ),
             ));
        $this->option('collate', 'latin1_spanish_ci');
        $this->option('charset', 'latin1');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Proyecto as ProyectoIdProyecto', array(
             'local' => 'Proyecto_idProyecto',
             'foreign' => 'idProyecto'));

        $this->hasOne('Persona as PersonaIdPersona', array(
             'local' => 'Persona_idPersona',
             'foreign' => 'idPersona'));
    }
}