<?php

/**
 * BaseSprintProductBacklog
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $Persona_id
 * @property integer $Sprint_id
 * @property integer $Productbacklog_id
 * @property clob $Anotaciones
 * @property Sprint $Sprint
 * @property Persona $Persona
 * @property Productbacklog $Productbacklog
 * 
 * @method integer              getId()                Returns the current record's "id" value
 * @method integer              getPersonaId()         Returns the current record's "Persona_id" value
 * @method integer              getSprintId()          Returns the current record's "Sprint_id" value
 * @method integer              getProductbacklogId()  Returns the current record's "Productbacklog_id" value
 * @method clob                 getAnotaciones()       Returns the current record's "Anotaciones" value
 * @method Sprint               getSprint()            Returns the current record's "Sprint" value
 * @method Persona              getPersona()           Returns the current record's "Persona" value
 * @method Productbacklog       getProductbacklog()    Returns the current record's "Productbacklog" value
 * @method SprintProductBacklog setId()                Sets the current record's "id" value
 * @method SprintProductBacklog setPersonaId()         Sets the current record's "Persona_id" value
 * @method SprintProductBacklog setSprintId()          Sets the current record's "Sprint_id" value
 * @method SprintProductBacklog setProductbacklogId()  Sets the current record's "Productbacklog_id" value
 * @method SprintProductBacklog setAnotaciones()       Sets the current record's "Anotaciones" value
 * @method SprintProductBacklog setSprint()            Sets the current record's "Sprint" value
 * @method SprintProductBacklog setPersona()           Sets the current record's "Persona" value
 * @method SprintProductBacklog setProductbacklog()    Sets the current record's "Productbacklog" value
 * 
 * @package    scrum
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSprintProductBacklog extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('sprint_product_backlog');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('Persona_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('Sprint_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('Productbacklog_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('Anotaciones', 'clob', 65535, array(
             'type' => 'clob',
             'length' => 65535,
             ));


        $this->index('fk_SprintProductBacklog_Sprint1', array(
             'fields' => 
             array(
              0 => 'Sprint_id',
             ),
             ));
        $this->index('fk_SprintProductBacklog_Persona1', array(
             'fields' => 
             array(
              0 => 'Persona_id',
             ),
             ));
        $this->index('fk_SprintProductBacklog_Productbacklog1', array(
             'fields' => 
             array(
              0 => 'Productbacklog_id',
             ),
             ));
        $this->option('collate', 'latin1_spanish_ci');
        $this->option('charset', 'latin1');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Sprint', array(
             'local' => 'Sprint_id',
             'foreign' => 'id'));

        $this->hasOne('Persona', array(
             'local' => 'Persona_id',
             'foreign' => 'id'));

        $this->hasOne('Productbacklog', array(
             'local' => 'Productbacklog_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}