<?php

/**
 * BaseCambio
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $Proyecto_id
 * @property integer $Persona_id
 * @property string $Descripcion
 * @property timestamp $Fecha
 * @property Persona $Persona
 * @property Proyecto $Proyecto
 * 
 * @method integer   getId()          Returns the current record's "id" value
 * @method integer   getProyectoId()  Returns the current record's "Proyecto_id" value
 * @method integer   getPersonaId()   Returns the current record's "Persona_id" value
 * @method string    getDescripcion() Returns the current record's "Descripcion" value
 * @method timestamp getFecha()       Returns the current record's "Fecha" value
 * @method Persona   getPersona()     Returns the current record's "Persona" value
 * @method Proyecto  getProyecto()    Returns the current record's "Proyecto" value
 * @method Cambio    setId()          Sets the current record's "id" value
 * @method Cambio    setProyectoId()  Sets the current record's "Proyecto_id" value
 * @method Cambio    setPersonaId()   Sets the current record's "Persona_id" value
 * @method Cambio    setDescripcion() Sets the current record's "Descripcion" value
 * @method Cambio    setFecha()       Sets the current record's "Fecha" value
 * @method Cambio    setPersona()     Sets the current record's "Persona" value
 * @method Cambio    setProyecto()    Sets the current record's "Proyecto" value
 * 
 * @package    scrum
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCambio extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('cambio');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('Proyecto_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('Persona_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('Descripcion', 'string', 150, array(
             'type' => 'string',
             'length' => 150,
             ));
        $this->hasColumn('Fecha', 'timestamp', null, array(
             'type' => 'timestamp',
             ));


        $this->index('fk_Cambios_Persona2', array(
             'fields' => 
             array(
              0 => 'Persona_id',
             ),
             ));
        $this->index('fk_Cambios_Proyecto2', array(
             'fields' => 
             array(
              0 => 'Proyecto_id',
             ),
             ));
        $this->option('collate', 'latin1_spanish_ci');
        $this->option('charset', 'latin1');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Persona', array(
             'local' => 'Persona_id',
             'foreign' => 'id'));

        $this->hasOne('Proyecto', array(
             'local' => 'Proyecto_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}