<?php

/**
 * ProductBacklogTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProductBacklogTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ProductBacklogTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ProductBacklog');
    }
}