<?php

/**
 * ReunionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ReunionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ReunionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Reunion');
    }
}