# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

default:
  http_metas:
    content-type: text/html
    charset: utf-8
  metas:
    #title:        symfony project
    #description:  symfony project
    #keywords:     symfony, project
    #language:     en
    #robots:       index, follow

  stylesheets:    [main.css,jTPS.css,style_light.css]

  javascripts:    [jquery.js,jTPS.js,jquery-ui-1.8.14.custom.min.js,ttw-notification-menu.min.js,tablaLista.js]

  has_layout:     true
  layout:         layout
