<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2012/09/10 21:23:33

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=scrum',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
