<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2012/09/10 21:34:49

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=scrum',
  'username' => 'root',
  'password' => 'root',
  'name' => 'doctrine',
)),);
