# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/12-Filters

rendering: ~

#yo (ludwing) agregué estas dos lineas:
remember_me:
  class: sfGuardRememberMeFilter

security:  ~

# insert your own filters here

cache:     ~
execution: ~
