<?php

/**
 * CambioTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CambioTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CambioTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Cambio');
    }

	public function getHistorialCambios($idproyecto, $idpersona)
	{
		$q=Doctrine_Query::create()
			->from('cambio c')
			->where ('c.proyecto_id = '.$idproyecto.' and c.persona_id = '.$idpersona);
		return $q->execute();
	}
	public function getHistorialCambiosPersona()
	{
		$q=Doctrine_Query::create()
			->from('cambio c')
			->where ('c.persona_id = '.$idpersona);
		return $q->execute();
	}
	
	public static function getUltimosCambios()
	{
		$q=Doctrine_Query::create()
			->from('cambio c')
			->orderBy('c.created_At desc')
			->limit(12);
		return $q->execute();
	}
}
