<?php

/**
 * CambioTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CambioTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CambioTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Cambio');
    }
}