<?php

/**
 * ProductBacklogTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProductBacklogTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ProductBacklogTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ProductBacklog')
			->createQuery('a')
			->where('proyecto_id='.$this->getUser()->getAttribute('proyecto'))
			->execute();
				
    }
	public function getProductBacklog($idproyecto)
	{
		if  ($idproyecto == null){
			$idproyecto = 0;
		}
		$q=Doctrine_Query::create()
				->from('productbacklog p')
				->where ('p.is_activated = 1 and p.proyecto_id = '.$idproyecto);
		return $q->execute();
	}
}
