<?php

/**
 * ProyectoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProyectoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ProyectoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Proyecto');
    }
	
	public static function getProyectos($idSfUser)
	{
		$q=Doctrine_Query::create()
			->from('Proyecto p')
			->where ('p.is_activated = 1 and (p.id IN (SELECT e.Proyecto_Id FROM Equipo e WHERE e.Persona_Id='.$idSfUser.') OR p.persona_id='.$idSfUser.')');
		return $q->execute();
	}
	public function getProyectosUsuario($idPersona)
	{
		$q=Doctrine_Query::create()
			->from('Proyecto p')
			->where ('p.is_activated = 1 and (p.id IN (SELECT e.Proyecto_Id FROM Equipo e WHERE e.Persona_Id='.$idPersona.') OR p.persona_id='.$idPersona.')');
		return $q->execute();
	}
}
