<?php

/**
 * SprintProductBacklogTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SprintProductBacklogTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SprintProductBacklogTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SprintProductBacklog');
    }

	public function getSprintProductBacklog($idproyecto)
	{
		if  ($idproyecto == null){
			$idproyecto = 0;
		}
			$q=Doctrine_Query::create()
				->from('SprintProductBacklog s')
				->where('s.sprint_id in (SELECT t.id FROM sprint t WHERE t.proyecto_id = '.$idproyecto.')');
		return $q->execute();
	}
	public function getProductBacklogs($idsprint)
	{
		$q=Doctrine_Query::create()
				->from('SprintProductBacklog s')
				->where('s.sprint_id = '.$idsprint);
		return $q->execute();
	}
}
