<?php

/**
 * SprintTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SprintTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SprintTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Sprint');
    }
}