Cambios:
  connection: doctrine
  tableName: cambios
  columns:
    idcambios:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    descripcion:
      type: string(150)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    fecha:
      type: timestamp(25)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    proyecto_idproyecto:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    persona_idpersona:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
  relations:
    Proyecto:
      local: proyecto_idproyecto
      foreign: idproyecto
      type: one
    Persona:
      local: persona_idpersona
      foreign: idpersona
      type: one
Equipo:
  connection: doctrine
  tableName: equipo
  columns:
    idequipo:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    idrol:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    idpersona:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    idproyecto:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    nombre:
      type: string(45)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    activo:
      type: integer(1)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
  relations:
    Rol:
      local: idrol
      foreign: idrol
      type: one
    Persona:
      local: idpersona
      foreign: idpersona
      type: one
    Proyecto:
      local: idproyecto
      foreign: idproyecto
      type: one
Estado:
  connection: doctrine
  tableName: estado
  columns:
    idestado:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    nombre:
      type: string(45)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    descripcion:
      type: string(45)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
  relations:
    Sprint:
      local: idestado
      foreign: idestado
      type: many
    Tarea:
      local: idestado
      foreign: idestado
      type: many
Historialchat:
  connection: doctrine
  tableName: historialchat
  columns:
    idhistorialchat:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    idpersona:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    idproyecto:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    mensaje:
      type: string(300)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    fecha:
      type: timestamp(25)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    activo:
      type: integer(1)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
  relations:
    Persona:
      local: idpersona
      foreign: idpersona
      type: one
    Proyecto:
      local: idproyecto
      foreign: idproyecto
      type: one
Link:
  connection: doctrine
  tableName: link
  columns:
    idlink:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    direccion:
      type: string(200)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    descripcion:
      type: string(200)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    idproyecto:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
  relations:
    Proyecto:
      local: idproyecto
      foreign: idproyecto
      type: one
Persona:
  connection: doctrine
  tableName: persona
  columns:
    idpersona:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    nombre:
      type: string(100)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    email:
      type: string(45)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    telefono:
      type: string(15)
      fixed: true
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    contraseã±a:
      type: blob()
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    activo:
      type: integer(1)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
  relations:
    Cambios:
      local: idpersona
      foreign: persona_idpersona
      type: many
    Equipo:
      local: idpersona
      foreign: idpersona
      type: many
    Historialchat:
      local: idpersona
      foreign: idpersona
      type: many
    Productbacklog:
      local: idpersona
      foreign: idpersona
      type: many
    Proyecto:
      local: idpersona
      foreign: idadministrador
      type: many
    Reunion:
      local: idpersona
      foreign: idpersona
      type: many
    Tarea:
      local: idpersona
      foreign: idpersona
      type: many
Productbacklog:
  connection: doctrine
  tableName: productbacklog
  columns:
    idproductbacklog:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    nombre:
      type: string(45)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    descripcion:
      type: string(100)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    prioridad:
      type: integer(1)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    duracion:
      type: integer(2)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    idproyecto:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    idpersona:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    activo:
      type: integer(1)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
  relations:
    Proyecto:
      local: idproyecto
      foreign: idproyecto
      type: one
    Persona:
      local: idpersona
      foreign: idpersona
      type: one
    Sprintproductbacklog:
      local: idproductbacklog
      foreign: idproductbacklog
      type: many
    Tarea:
      local: idproductbacklog
      foreign: idproductbacklog
      type: many
Proyecto:
  connection: doctrine
  tableName: proyecto
  columns:
    idproyecto:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    idadministrador:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    nombre:
      type: string(45)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    descripcion:
      type: string(100)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    comentarios:
      type: string(100)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    fcreacion:
      type: timestamp(25)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    fmodificacion:
      type: timestamp(25)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    ffinalizacion:
      type: timestamp(25)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    activo:
      type: integer(1)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
  relations:
    Persona:
      local: idadministrador
      foreign: idpersona
      type: one
    Cambios:
      local: idproyecto
      foreign: proyecto_idproyecto
      type: many
    Equipo:
      local: idproyecto
      foreign: idproyecto
      type: many
    Historialchat:
      local: idproyecto
      foreign: idproyecto
      type: many
    Link:
      local: idproyecto
      foreign: idproyecto
      type: many
    Productbacklog:
      local: idproyecto
      foreign: idproyecto
      type: many
    Reunion:
      local: idproyecto
      foreign: idproyecto
      type: many
Reunion:
  connection: doctrine
  tableName: reunion
  columns:
    idreunion:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    titulo:
      type: string(45)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    descripcion:
      type: string(45)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    anotaciones:
      type: string(45)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    fecha:
      type: timestamp(25)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    duracion:
      type: integer(1)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    idproyecto:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    idpersona:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    activo:
      type: integer(1)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
  relations:
    Proyecto:
      local: idproyecto
      foreign: idproyecto
      type: one
    Persona:
      local: idpersona
      foreign: idpersona
      type: one
Rol:
  connection: doctrine
  tableName: rol
  columns:
    idrol:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    nombre:
      type: string(45)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    descripcion:
      type: string(100)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    activo:
      type: integer(1)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
  relations:
    Equipo:
      local: idrol
      foreign: idrol
      type: many
Sprint:
  connection: doctrine
  tableName: sprint
  columns:
    idsprint:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    nombre:
      type: string(45)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    descripcion:
      type: string(100)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    fechainicio:
      type: timestamp(25)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    fechafin:
      type: timestamp(25)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    diasdisponibles:
      type: integer(2)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    idestado:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
  relations:
    Estado:
      local: idestado
      foreign: idestado
      type: one
    Sprintproductbacklog:
      local: idsprint
      foreign: idsprint
      type: many
Sprintproductbacklog:
  connection: doctrine
  tableName: sprintproductbacklog
  columns:
    idsprint:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: false
    idproductbacklog:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: false
  relations:
    Sprint:
      local: idsprint
      foreign: idsprint
      type: one
    Productbacklog:
      local: idproductbacklog
      foreign: idproductbacklog
      type: one
Tarea:
  connection: doctrine
  tableName: tarea
  columns:
    idtarea:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    nombre:
      type: string(45)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    descripcion:
      type: string(45)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    tiempoestimado:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    idproductbacklog:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    idestado:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    idpersona:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
  relations:
    Productbacklog:
      local: idproductbacklog
      foreign: idproductbacklog
      type: one
    Estado:
      local: idestado
      foreign: idestado
      type: one
    Persona:
      local: idpersona
      foreign: idpersona
      type: one
